apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellothere-db
  namespace: hellothere
  labels:
    app: hellothere-db
spec:
  selector:
    matchLabels:
      app: hellothere-db
  template:
    metadata:
      labels:
        app: hellothere-db
    spec:
      containers:
        - name: hellothere-db
          image: mariadb:focal
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbcreds
                  key: password

---
kind: Service
apiVersion: v1
metadata:
  name: hellothere-db
  namespace: hellothere
spec:
  selector:
    app: hellothere-db
  ports:
    - port: 3306
