apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellothere-web
  namespace: hellothere
  labels:
    app: hellothere-web
spec:
  selector:
    matchLabels:
      app: hellothere-web
  template:
    metadata:
      labels:
        app: hellothere-web
    spec:
      containers:
        - name: hellothere-web
          image: havardei/php7:apache-buster-mysql
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: dbcreds
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbcreds
                  key: password
            - name: DBNAME
              valueFrom:
                secretKeyRef:
                  name: dbcreds
                  key: dbname
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: hellothere-web
  namespace: hellothere
spec:
  selector:
    app: hellothere-web
  ports:
    - port: 80

---
apiVersion: networking.k8s.io/v1    
kind: Ingress
metadata:
  name: hellothere-web  
  namespace: hellothere
spec:
  rules:
  - host: hellothere.localhost
    http:
      paths:
      - backend:
          service:
            name:  hellothere-web
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - hellothere.localhost
    secretName: wildcard-tls
