#!/bin/sh
set -e

git clone https://github.com/havardei/hellothere /tmp/hellothere
cp /tmp/hellothere/html/index.php /var/www/html/.

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"

