on: push
name: deploy to cluster
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy db
      uses: steebchen/kubectl@v2.0.0
      with: # defaults to latest kubectl binary version
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: apply -f $GITHUB_WORKSPACE/app_db.yaml
    - name: deploy web
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: apply -f $GITHUB_WORKSPACE/app_web.yaml
    - name: make sure all containers restart
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: delete pods --all
